### ISSUE TITLE
Sprites are all funky and rotated

### ISSUE THREAD

**Issue by cryogee** [DragonBones/DragonBonesCSharp#10]
My sprites are all funky and rotated. But when I uncomment the line 499 in UnitySlot.cs it seems to render correctly. Why is that portion commented out?
![screen shot 2016-11-30 at 6 18 08 pm](https://cloud.githubusercontent.com/assets/9545771/20752853/7fbeadf0-b729-11e6-8268-4baab6ab8269.png)

**Comment by akdcl** [comment]
Hi,
The bug has been fixed.
