### ISSUE TITLE
Bug on starting the game with two unique Armatures

### ISSUE THREAD

**Issue by toadietechnika** [DragonBones/DragonBonesCSharp#12]
I've tested the animations on the Unity workspace while the game is not playing, they're fine. But when I start the game, the other armature creates a cloned armature of the other.

GIF: (My play tint is light green)
![issuebones](https://cloud.githubusercontent.com/assets/4543674/20858428/ee2949e6-b97f-11e6-9499-f04532128117.gif)

**Comment by toadietechnika** [comment]
Found a fix for this, but it requires another script where you can serialize a string. This will allow you to have more than 1 unique armatures in the game.

![fix](https://cloud.githubusercontent.com/assets/4543674/20858919/97dad8ce-b98a-11e6-886d-592ac1235a5b.png)

**Comment by namudz** [comment]
Thanks @toadietechnika for the fix, today I encountered the same issue handling multiple armatures.
I tried your approach and works well but I also tried just passing the **`armatureName`** as the 2nd and 3rd parameter too and seems to work as well. This way is not necessary to have an extra script:

**`UnityFactory.factory.BuildArmatureComponent (armatureName, armatureName, armatureName, this.gameObject)`**

Hope it works

**Comment by toadietechnika** [comment]
I've thought of that before but still mess up sometimes. If we didn't name the Armature on DragonBones Pro (something with the "Armature" default name, it's the one at the top most then next is the Root) then it would cause that error. It's weird that the bug may occur or not, so I've used another script to avoid taking that risk :D

**Comment by akdcl** [comment]
Hi,
The rename bug has been fixed.

**Comment by toadietechnika** [comment]
Gotcha, thank you very much for that fix on the rename bug. Although I haven't checked in Unity if that bugfix also fixed the bug in this post, I'll show it if it's fixed that bug as well.

**Comment by toadietechnika** [comment]
I'll close this because it's already fix on the updated API. Thank you very much :D
