### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by toadietechnika** [DragonBones/DragonBonesCSharp#13]
I have a game object with a "Unity Armature Component" because I want to organize my game objects in the scene properly, while the armature's textures are present. I name my gameobjects for descriptive purposes, but they revert to "Armature" when Unity is in game mode.

![issuerename](https://cloud.githubusercontent.com/assets/4543674/20858611/b9af60ca-b983-11e6-8150-8a4b3ab9bc67.gif)

**Comment by toadietechnika** [comment]
I've checked that the name in the hierarchy will also depend on how you did it on DragonBones, but still I want to rename them in Unity.

**Comment by akdcl** [comment]
Hi,
The bug has been fixed.
