### ISSUE TITLE
How to use animation mixing

### ISSUE THREAD

**Issue by JamesAMD** [DragonBones/DragonBonesCSharp#16]
Hello, on DragonBones features page, it mentions animation mixing using layers (normal weighting) and groups (additive weighting).

Can someone shed a light on how to use these features ?
I do know there are parameters for them in `DragonBone.Animation.FadeIn` method, but I'm not exactly sure how to use them.
Also, I see no option for animation layers or groups in DragonBonesPro Editor.

I'd really appreciate any help, since I'm getting pretty desperate because of lack of documentations.
Thanks in advance !

**Comment by toadietechnika** [comment]
There's a parameter for an Animation Layer (int) for Animation.FadeIn, I think it's the 3rd or 4th. I'll send the exact code later on since there's no Dragonbones on the Computer I am using. :D

**Comment by toadietechnika** [comment]
Here you go (The one in Bold-Italic is the parameter, so it's the fourth one. The default layer is 0, so if you play an animation in another layer then it will play in another layer (in short, it will be mixed with the other animations)):

FadeIn(
            string animationName, float fadeInTime = -1.0f, int playTimes = -1,
            <i><b>int layer = 0</b></i>, string group = null, AnimationFadeOutMode fadeOutMode = AnimationFadeOutMode.SameLayerAndGroup,
            bool additiveBlending = false, bool displayControl = true,
            bool pauseFadeOut = true, bool pauseFadeIn = true
        )

**Comment by JamesAMD** [comment]
Thank you for your response ! I wasn't expecting to get one this fast.

So that's why I don't see any option for layers in DragonBonesPro Editor.
I think I'm getting the hang of it now.

Another question, if I may :
Am I correct in thinking there's no way to use different animations for different bones (and not blending them)?
For example, I might want to use the animation "walk" when just walking normally, which moves all limbs.
But when attacking while walking, I might want to use "walk" on legs but "attack" on arms (which would override the movements "walk" has on arms).

I know this can be done in Unity's 3D Mecanim system, using the Mask mechanism.
I also see `AddBoneMask(string)` method in `DragonBones.AnimationState` class, but I'm having difficulty figuring out how it works.

Currently I'm using nested armature and layer system (thanks to you!) and so far it's working fairy decently.
But it would be nice to know if there's something like Mecanim's Mask system in DragonBones.
Thanks in advance :)

**Comment by toadietechnika** [comment]
Yeah, it's in the codes of Dragon Bones. I've had difficulties too at first because of lacking documentations, fortunately we can also view and analyze their codes and see what they do :D

In response to your question:
I haven't tried that, but my guess for now (... and someone would also enlighten me on this if I gave some wrong information haha but anyway - ) is you can't overlap animations that way (of just getting bones from this animation, overriding the other bones of that animation). So I think blending is the only way to achieve that. 

That would also depend on the keyframes affecting on the animations. When blending, the bones without keyframes of this animation will affect from the blending animation, otherwise it would mess up (sort of-).

To be honest, I haven't heard of a "Mecanim's Mask System" on Dragonbones so I gotta see what else is there.
Glad you're doing well on it, keep it up!

**Comment by JamesAMD** [comment]
So, there isn't anything like `AvatarMask `in DragonBones animation system (just not yet, I hope !)...

Thank you for your time, I really appreciate it.
I might ask another question some time soon, I'd be grateful if I could get your help again :)

Closing now !

**Comment by PraveenKrishna07** [comment]
> 
> 
> Yeah, it's in the codes of Dragon Bones. I've had difficulties too at first because of lacking documentations, fortunately we can also view and analyze their codes and see what they do :D
> 
> In response to your question:
> I haven't tried that, but my guess for now (... and someone would also enlighten me on this if I gave some wrong information haha but anyway - ) is you can't overlap animations that way (of just getting bones from this animation, overriding the other bones of that animation). So I think blending is the only way to achieve that.
> 
> That would also depend on the keyframes affecting on the animations. When blending, the bones without keyframes of this animation will affect from the blending animation, otherwise it would mess up (sort of-).
> 
> To be honest, I haven't heard of a "Mecanim's Mask System" on Dragonbones so I gotta see what else is there.
> Glad you're doing well on it, keep it up!

is there any way to use dragon bones with unity built in animator?
