### ISSUE TITLE
If scene is switched,  the animations are not shown 

### ISSUE THREAD

**Issue by attilix** [DragonBones/DragonBonesCSharp#23]
As title says, this problem occurs only after I switch rooms, after getting some debug info I got this messages. I tried with demos, but the same error occurs. I tried both methods to build the UnityArmatureComponent, by runtime or by getting it an already created UnityArmatureComponent,
it actually works on the editor but if you export it in the first case nothing is shown in the second case the base body is loaded but no animation are played.
![08c35959-1e29-402b-935d-f949b9c03c00](https://cloud.githubusercontent.com/assets/17616408/22943692/c682f1dc-f2ee-11e6-831c-b34f549ad8ac.jpg)

**Comment by akdcl** [comment]
Hi,
We will find the problem and fix the bug as soon as possible.

**Comment by akdcl** [comment]
Hi, the bug has been fixed.

**Comment by attilix** [comment]
Nice! I think that you`re doing a great job, keep going like this.
P.S Dragon bones would be way better with a nice api documentation, you know the majority it`s in chinese.
