### ISSUE TITLE
When I use SceneManager.LoadScene(), the Animation is broken (on mobile only)

### ISSUE THREAD

**Issue by Melix19** [DragonBones/DragonBonesCSharp#24]
The problem occurs when i change the scene where the animation is located, to another and I return back to the previous one. The animation is not created.
This occurs on mobile only (tested on Android and iOS), on Windows and macOS works perfectly.

xCode Debug gave me this:

![schermata 2017-02-19 alle 15 26 12](https://cloud.githubusercontent.com/assets/23530586/23103220/d6c2cd84-f6b7-11e6-8c42-ace5f84ccff2.png)

**Comment by akdcl** [comment]
Hi,
We will find the problem and fix the bug as soon as possible.

**Comment by akdcl** [comment]
Hi, the bug has been fixed.

**Comment by Melix19** [comment]
Nice! Now I can continue with my project with this fantastic tool :) Many thanks!
