### ISSUE TITLE
使用ReplaceSlotDisplay图片资源偏移

### ISSUE THREAD

**Issue by LetitiaChan** [DragonBones/DragonBonesCSharp#27]
在动画帧事件中，使用ReplaceSlotDisplay替换图片资源，替换后的位置偏移Bug，有什么办法可以规避呢？被替换的插槽资源是在运动的，想要整体往上偏移一点点。
或者说 怎么调整 Slot的位置，往上偏移，并且作用于整个Slot的动画中。

http://developer.egret.com/cn/github/egret-docs/DB/dbLibs/replaceTexture/index.html
这个链接中描述的是整个换资源包，我想要局部替换资源，所有资源都打在一个png里。

**Comment by zhouzhanglin** [comment]
是不是替换的图片大小宽高不正确，因为图集里面的有些图片是进行了Trim的。
如果你想修改，可以仿照ReplaceSlotDisplay自己写一个方法，在newDisplayData.transform.CopyFrom(prevDispalyData.transform);这行后面，修改newDisplayData.transform的 x, y值

**Comment by LetitiaChan** [comment]
嗯，解决了。
Slot tar = armatureComponent.armature.GetSlot("tiao8");
tar.offset.x = tar.offset.x + 0.14f;
tar._updateTransformAndMatrix();
我加了偏移量offset，然后更新变幻矩阵，可以了。
谢谢你
