### ISSUE TITLE
Enable Wiki?

### ISSUE THREAD

**Issue by nanopony** [DragonBones/DragonBonesCSharp#28]
Hello!

First of all, I'd like to thank you for making such an amazing project available free of charge -- it has every single feature gamedev needs. The only thing that prevents it from taking deserved attention is a small amount of English documentation.

I picked it to use for my game and I'd like to contribute my experience to help other people using DragonBones with Unity. Wiki is an excellent choice for collaborative documentation writing.

Could you please consider enabling wiki section on this repo?

**Comment by akdcl** [comment]
Hi,
Thank you for you contribute, the wiki has been enabled :)

**Comment by nanopony** [comment]
Thank you! I've already started writing, soon I'll put the first content in wiki!
