### ISSUE TITLE
obselete methods..

### ISSUE THREAD

**Issue by nemesiscy** [DragonBones/DragonBonesCSharp#34]
UnityFactory.factory.LoadDragonBonesData("Ubbie/Ubbie"); // DragonBones file path (without suffix)
UnityFactory.factory.LoadTextureAtlasData("Ubbie/texture"); //Texture atlas file path (without suffix) 
these functions have become obselete... how do i use the LoadData?

**Comment by chojuhyeong** [comment]
+1

**Comment by zhouzhanglin** [comment]
- Select the ske file
- right-click -> Create -> DragonBones ->Armature Object / Armature Object (UGUI)

**Comment by chojuhyeong** [comment]
I am working on version 2.3 of the Dragon Bones animation.
Your answer has been helpful enough for me.
Thank you.
 
i'm 2.3ver DragonBones testing
 
-----Original Message-----
