### ISSUE TITLE
What is the skinName meaning?

### ISSUE THREAD

**Issue by zzzxxccvv** [DragonBones/DragonBonesCSharp#41]
in this function:
`
public UnityArmatureComponent BuildArmatureComponent(string armatureName, string dragonBonesName = null, string skinName = null, string textureAtlasName = null, GameObject gameObject = null,bool isUGUI=false);
`

How to make more than one skin in DragonBonesPro Editor?
(I can only change the export json file to make it work.)

while, I also can not find the way to change a suit of pictures for one skeleton

**Comment by akdcl** [comment]
Hi, DragonBonesPro Editor can not support more than one skin yet. (but dragonBones runtime support it)
We will support skin share in dragonBones runtime 5.5 （armature can user other armature skin）.
```
factory.changeSkin(armature, otherArmatureSkinData);
```
[The changeSkin demo online](http://dragonbones.com/demo/egret/core_element/)
The csharp db 5.5 run still in development, it will be released by the end of October.
