### ISSUE TITLE
最新的Unity代码ReplaceSlotDisplay一个非网格的Slot之后会看不见

### ISSUE THREAD

**Issue by sherocyc** [DragonBones/DragonBonesCSharp#43]
最新的Unity代码ReplaceSlotDisplay一个非网格的Slot之后会看不见，网格的才可以看见。demo里的Ubbie就可以复现

**Comment by sherocyc** [comment]
之前没有这个问题，更新之后才有的

**Comment by wuliao2230** [comment]
你好，你发现的问题，我们测试后，确实也发现了,UGUI替换后slot都会看不见，问题已经找到，我们会尽量修复，不过可能近期无法更新到git上。
普通的Armatrue，我们测试却没有重现你所说的问题，如果你那里可以必现的话，方便提供测试工程吗？

**Comment by sherocyc** [comment]
你们demo里的ubbie就可以复现的。demo里的是替换了pifeng这个插槽，这个插槽是网格。你替换一个不是网格的插槽，比如嘴巴，都可以复现。

**Comment by sherocyc** [comment]
在之前的版本中，替换非网格的插槽都是正常的。

**Comment by sherocyc** [comment]
请问问题解决了吗？

**Comment by wuliao2230** [comment]
你好，这个问题我们已经解决，不过要在近期的下一个版本中发布

**Comment by wuliao2230** [comment]
我们已经更新了，插槽问题也包括其中，你可以更新下试试

**Comment by sherocyc** [comment]
最新版本我试了。demo里的方式确实可以正常工作，替换一个atlas里的图片。但是我替换一个Texture2D之后，依然不可见。

**Comment by wuliao2230** [comment]
有警告提示吗？你是用UGUI模式下替换的，还是正常的模式下替换的

**Comment by sherocyc** [comment]
没有警告 正常模式 我是用你们demo测试的 那个机器人 不是UGUI

**Comment by sherocyc** [comment]
ReplaceSlotDisplay有一个重载是带有Texture2D参数的 那个方法替换一个图片进去
