### ISSUE TITLE
Get a null if instantiate data from Unity editor

### ISSUE THREAD

**Issue by Airat1995** [DragonBones/DragonBonesCSharp#45]
Hi! Can I play an animation from code if I created it from the editor and saved as prefab? 
Why if I use code like that I got and NullRefrenceException?
` dgb.GetComponent<UnityArmatureComponent>().animation.Play("Calm");`
Or I must define data from code to make unit animated?

**Comment by wuliao2230** [comment]
Yes, you can play an animation from code.
I guess the error was caused by the previous reference(dgb or UnityArmatureComponent or animation).
You can find out which reference is empty at the breakpoint.

**Comment by Airat1995** [comment]
Ok, thanks. Mb lost animation somewhere.
