### ISSUE TITLE
20171201的版本，匯入Unity後骨頭不會轉

### ISSUE THREAD

**Issue by KyokuHo** [DragonBones/DragonBonesCSharp#46]
2017/12/01的版本，匯入Unity後骨頭不會轉動，導至綁定在手腳的Clidder無法正確運作，在舊版的是沒問題的。

**Comment by wuliao2230** [comment]
导出的资源方便传一份吗？我好方便定位问题

**Comment by KyokuHo** [comment]
[iRinDB.zip](https://github.com/DragonBones/DragonBonesCSharp/files/1528052/iRinDB.zip)
附檔是我導出的資源檔，我使用12/1版本將一個Empty放到腳的骨頭下面做子物件，並不會跟著轉，但在先前的版本是可以的，我朋友也發生相同的問題。

**Comment by wuliao2230** [comment]
你好，这个Bug已经修改，更新一下应该就可以了

**Comment by KyokuHo** [comment]
速度好快，太感謝了
