### ISSUE TITLE
导入的UGUI层的bones动画不会动

### ISSUE THREAD

**Issue by pengjoy** [DragonBones/DragonBonesCSharp#48]
导入的UGUI层的bones动画不会动，Create->Armature(UGUI)，但如果非UGUI的是会动的。
1.layer也设置好了，相机没有问题，在Scene场景能看到
2.是在canvas下面并且层级正确

**Comment by wuliao2230** [comment]
更新最新的运行时就可以解决了

**Comment by pengjoy** [comment]
问题已经修正， 2018-1-29 GitHub版本，谢谢。
