### ISSUE TITLE
菜单里Reload使用会报错

### ISSUE THREAD

**Issue by LueSanTuo** [DragonBones/DragonBonesCSharp#49]
之前和reload相关的函数调用后悔出现动画错乱。现在按inspector面板里的reload直接就报错了。不知是不是我操作的问题。

**Comment by wuliao2230** [comment]
非常感谢你的反馈，dev分支已经修复这个问题。

**Comment by LueSanTuo** [comment]
NullReferenceException: Object reference not set to an instance of an object
DragonBones.UnityArmatureEditor.OnInspectorGUI () (at Assets/DragonBones/Editor/UnityArmatureEditor.cs:318)
不过我按inspector面板里的reload还是出现错误。

**Comment by wuliao2230** [comment]
是的，不过这个bug已经在dev分支修复，你可以更新下。

**Comment by LueSanTuo** [comment]
嗯。。重新下载了代码。新建工程放进去还是报错。
对了还有个问题就是。Assets/Scripts/unity/UnityArmatureComponent.cs(270,45): error CS0117: `UnityEngine.GL' does not contain a definition for `LINE_STRIP'
这LINE_STRIP在5.5没有。换成LINES应该不影响运行的吧。

**Comment by wuliao2230** [comment]
这个不影响，reload报错还有吗？如果还有报错的话，你可以看下UnityArmatureEditor中ClearUp函数_sortingLayerNames应该是注释掉了，如果没有注释掉，就说明你下载的不是最新的dev分支

**Comment by LueSanTuo** [comment]
确实没有注释掉。
难道最新的dev分支不在这里下么。【害怕】
https://github.com/DragonBones/DragonBonesCSharp

**Comment by wuliao2230** [comment]
哦，你用的是master分支，master分支还没有合并到最新的代码，只有切换到dev分支才可以。不过这个bug如果不影响你使用的话，也可以不急着更新，等下次master分支更新也可以。

**Comment by LueSanTuo** [comment]
这样子阿。我不清楚master和dev用起来有啥不一样。哈。

**Comment by wuliao2230** [comment]
master是稳定版，dev是开发版
