### ISSUE TITLE
停止运行游戏后骨骼重叠

### ISSUE THREAD

**Issue by kongyuan** [DragonBones/DragonBonesCSharp#6]
最新的da9229e版本
将骨骼对象放在舞台中, 运行游戏, 停止运行, 所有骨骼会丢失坐标重叠在一起, 同时console会报很多错误
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.EditorGUIUtility.TempContent (System.String[] texts) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIUtilityBindings.gen.cs:313)
UnityEditor.EditorGUI.Popup (Rect position, System.String label, Int32 selectedIndex, System.String[] displayedOptions, UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:570)
UnityEditor.EditorGUILayout.Popup (System.String label, Int32 selectedIndex, System.String[] displayedOptions, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6194)
UnityEditor.EditorGUILayout.Popup (System.String label, Int32 selectedIndex, System.String[] displayedOptions, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6187)
DragonBones.UnityArmatureEditor.OnInspectorGUI () (at Assets/DragonBones/unity/Editor/UnityEditor.cs:215)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1235)
UnityEditor.DockArea:OnGUI()

**Comment by akdcl** [comment]
这个 bug 已经修复了 ， editor 的功能还在逐步的完善
